#!/usr/bin/env bash

# go tool dist list

GOOS=linux GOARCH=arm go build -a -o ./releases/bullettrain.linux-arm bullettrain.go
sha256sum -b ./releases/bullettrain.linux-arm > ./releases/bullettrain.linux-arm.sha256

GOOS=linux GOARCH=arm64 go build -a -o ./releases/bullettrain.linux-arm64 bullettrain.go
sha256sum -b ./releases/bullettrain.linux-arm64 > ./releases/bullettrain.linux-arm64.sha256

GOOS=linux GOARCH=386 go build -a -o ./releases/bullettrain.linux-386 bullettrain.go
sha256sum -b ./releases/bullettrain.linux-386 > ./releases/bullettrain.linux-386.sha256

GOOS=linux GOARCH=amd64 go build -a -o ./releases/bullettrain.linux-amd64 bullettrain.go
sha256sum -b ./releases/bullettrain.linux-amd64 > ./releases/bullettrain.linux-amd64.sha256

GOOS=darwin GOARCH=amd64 go build -a -o ./releases/bullettrain.darwin-amd64 bullettrain.go
sha256sum -b ./releases/bullettrain.darwin-amd64 > ./releases/bullettrain.darwin-amd64.sha256
